(() => {
'use strict';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:NaN;};
const price=x=>{if(!Number.isFinite(Number(x)))return '—';const n=Number(x),a=Math.abs(n),d=a>=1000?2:a>=1?4:a>=.01?6:8;return n.toFixed(d).replace(/0+$/,'').replace(/\.$/,'');};
const compact=x=>Number.isFinite(Number(x))?new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(Number(x)):'—';
function resultPill(r){return `<span class="pill ${String(r||'').toLowerCase()}">${esc(r||'—')}</span>`;}
function reason(r){const watchReason=String(r?.autoWatchReason||'').trim();if(watchReason)return `Watch ${String(r?.autoWatchStatus||'WAIT').toUpperCase()} | ${watchReason}`;const c=r?.chartAnalysis;if(!c)return r?.result||'—';const tf=r?.scanTimeframes||{};const trend=tf.trend||'5m',setup=tf.setup||'3m',confirm=tf.confirm||'1m';const p=[r.result==='SELECT'?'ENTRY READY':r.result];if(c.step7?.regime)p.push(`${trend} ${c.step7.regime}`);if(c.step8?.setup)p.push(`${setup} ${c.step8.setup}`);if(c.step9?.score)p.push(`${confirm} ${c.step9.score}`);if(c.step10?.status)p.push(c.step10.status);return p.filter(Boolean).join(' | ');}
function watchHtml(r){const status=r?.autoWatchStatus?String(r.autoWatchStatus).toUpperCase():'OFF';const cls=status==='GREEN'?'green':status==='ARMED'||status==='WAIT'?'yellow':status==='RED'?'red':'off';const title=String(r?.autoWatchReason||status);return `<div class="watchCell"><span class="watchSignal ${cls}" title="${esc(title)}"><span class="watchSignalDot"></span>${esc(status)}</span></div>`;}
function scanLabel(r){const s=String(r?.scanSource||'Auto Scan');return s.replace(/^Auto\s+/i,'').replace(/\s+Scan$/i,'');}
function rowHtml(r,i){const g=r.gridMeta||{},pl=r.decisionSupport?.priceLevel?.label||'—',rl=r.decisionSupport?.riskLevel?.label||'—';return `<tr data-symbol="${esc(r.symbol)}" data-scan-source="${esc(r.scanSource||'Auto Scan')}">
<td>${i+1}</td><td class="symbol"><button class="symbolBtn" data-action="decision-support" data-symbol="${esc(r.symbol)}" type="button">${esc(r.symbol)}</button></td>
<td data-role="ys">${g.ys===true?'✓':g.ys===false?'✕':'—'}</td><td>${watchHtml(r)}</td><td>${resultPill(r.result)}</td><td data-role="price-level">${esc(pl)}</td><td data-role="risk-level">${esc(rl)}</td>
<td><input class="monitorInput entryPriceInput" data-role="entry" type="number" min="0" step="any" placeholder="Entry Price" inputmode="decimal"></td>
<td><input class="monitorInput stopPriceInput" data-role="stop" type="number" min="0" step="any" placeholder="Stop Price" inputmode="decimal"></td>
<td class="num" data-role="current-price">${esc(price(Number.isFinite(r.decisionPrice)?r.decisionPrice:r.snapshot2))}</td><td><button class="followBtn" data-action="follow" data-symbol="${esc(r.symbol)}" type="button">Follow</button></td>
<td class="monitorCell"><span class="monitorDot off" title="OFF"></span></td><td class="monitorReason"><span class="reasonText">${esc(reason(r))}</span><div class="monitorTime"></div></td><td class="liveChangeCell" data-role="live-change"></td><td class="liveResultCell" data-role="live-result"></td><td>${esc(scanLabel(r))}</td>
<td class="num" data-role="meta-volume">${esc(compact(g.volume24h))}</td><td class="num" data-role="meta-total-supply">${esc(compact(g.totalSupply))}</td><td class="num" data-role="meta-circ-supply">${esc(compact(g.circulatingSupply))}</td><td class="metaAge" data-role="meta-age">—</td><td class="num" data-role="meta-max">${esc(price(g.allTimeHigh))}</td><td class="num" data-role="meta-min">${esc(price(g.allTimeLow))}</td><td data-role="meta-hour">${esc(g.requestTime||'—')}</td></tr>`;}
class AutoScanUI{
 get(id){return document.getElementById(id);} queryAll(s){return [...document.querySelectorAll(s)];}
 log(msg){const e=this.get('logBox');if(!e)return;const t=new Date().toLocaleTimeString('tr-TR');e.textContent+=`\n[${t}] ${msg}`;e.scrollTop=e.scrollHeight;}
 status(text,cls='info'){const e=this.get('mainStatus');if(e){e.textContent=text;e.className=`status ${cls}`;}}
 progress(v,text){v=Math.max(0,Math.min(100,Number(v)||0));const b=this.get('progressBar'),p=this.get('progressText'),s=this.get('stageText');if(b)b.style.width=`${v}%`;if(p)p.textContent=`${Math.round(v)}%`;if(s)s.textContent=text||'';}
 render(rows,watchStates=[]){const body=this.get('candidateBody');if(!body)return;const preserved=window.CryptoFlowScanner?.modules?.follow?.getPreservedRows?.()||[],ps=new Set(preserved.map(x=>x.symbol)),fresh=(rows||[]).filter(x=>!ps.has(x.symbol)),all=[...preserved,...fresh];body.innerHTML=all.length?all.map(rowHtml).join(''):'<tr><td colspan="16" class="empty">Bu scan için aday yok.</td></tr>';for(const w of watchStates||[]){const tr=this.queryAll('#candidateBody tr[data-symbol]').find(x=>x.dataset.symbol===w.symbol);const rt=tr?.querySelector('.reasonText');if(rt){rt.textContent=`Watch ${w.status} | ${w.reason}`;rt.title=w.reason;}}document.dispatchEvent(new CustomEvent('cryptooffer:candidates-rendered'));}
 prepareFollowInputs(symbol,fallbackPrice){const tr=this.queryAll('#candidateBody tr[data-symbol]').find(x=>x.dataset.symbol===symbol);if(!tr)return false;const e=tr.querySelector('[data-role="entry"]'),s=tr.querySelector('[data-role="stop"]');if(!e||!s)return false;let entry=num(e.value);if(!(entry>0)){entry=num(String(tr.querySelector('[data-role="current-price"]')?.textContent||'').replace(/,/g,''));if(!(entry>0))entry=fallbackPrice;if(entry>0)e.value=String(Number(entry.toPrecision(12)));}let stop=num(s.value);if(!(stop>0)&&entry>0){stop=entry*.98;s.value=String(Number(stop.toPrecision(12)));}return entry>0&&stop>0&&stop<entry;}
 handle(evt){if(!evt)return;switch(evt.type){case'log':this.log(evt.message);break;case'status':this.status(evt.text,evt.className);break;case'progress':this.progress(evt.value,evt.text);break;case'results':case'auto-grid':this.render(evt.rows,evt.watchStates);break;case'reset':{const b=this.get('candidateBody');if(b)b.innerHTML='<tr><td colspan="16" class="empty">Scan çalışıyor…</td></tr>';break;}}}
}
globalThis.AutoScanUI=AutoScanUI;
})();
