(() => {
  'use strict';
  const DEFAULTS=Object.freeze({marketEndpoint:'wss://fstream.binance.com/market',publicEndpoint:'wss://fstream.binance.com/public',streamsPerSocket:160,reconnectMaxMs:15000,staleMs:15000,candleLimit:300,requiredTimeframes:['5m','3m','1m']});
  const n=v=>{const x=Number(v);return Number.isFinite(x)?x:NaN;};
  class MarketDataStore{
    constructor(options={}){this.options={...DEFAULTS,...options};this.symbols=new Map();this.books=new Map();this.priceHistory=new Map();}
    _symbol(symbol){let s=this.symbols.get(symbol);if(!s){s={intervals:new Map()};this.symbols.set(symbol,s);}return s;}
    _interval(symbol,interval){const s=this._symbol(symbol);let v=s.intervals.get(interval);if(!v){v={closed:[],current:null,bootstrapped:false,lastEventTime:0};s.intervals.set(interval,v);}return v;}
    seedBooks(rows){for(const b of Array.isArray(rows)?rows:[]){const symbol=String(b?.symbol||'');if(symbol)this.applyBook({s:symbol,b:b.bidPrice,a:b.askPrice,E:Number(b.time)||Date.now()},false);}}
    applyBook(data,fromWebSocket=true){const symbol=String(data?.s||data?.symbol||''),bid=n(data?.b??data?.bidPrice),ask=n(data?.a??data?.askPrice);if(!symbol||!(bid>0)||!(ask>0))return;const ts=Number(data?.E)||Date.now(),prev=this.books.get(symbol);this.books.set(symbol,{symbol,bidPrice:String(bid),askPrice:String(ask),time:ts,wsTime:fromWebSocket?ts:(Number(prev?.wsTime)||0)});this.recordPrice(symbol,(bid+ask)/2,ts);}
    seedInterval(symbol,interval,candles,serverTime){const slot=this._interval(symbol,interval),all=(Array.isArray(candles)?candles:[]).filter(c=>Number.isFinite(c.openTime)&&Number.isFinite(c.closeTime)),closed=all.filter(c=>c.closeTime<serverTime),current=all.find(c=>c.openTime<=serverTime&&c.closeTime>=serverTime)||null,keep=this.options.candleLimit+30,merged=new Map();for(const c of closed.slice(-keep))merged.set(c.openTime,c);for(const c of slot.closed)merged.set(c.openTime,c);slot.closed=[...merged.values()].sort((a,b)=>a.openTime-b.openTime).slice(-keep);if(!slot.current||(current&&slot.current.openTime<=current.openTime))slot.current=current;slot.bootstrapped=slot.closed.length>=this.options.candleLimit;return slot.bootstrapped;}
    applyKline(data){const k=data?.k;if(!k)return;const symbol=String(data?.s||k?.s||''),interval=String(k?.i||'');if(!symbol||!['1m','3m','5m','15m'].includes(interval))return;const slot=this._interval(symbol,interval),candle={openTime:Number(k.t),open:n(k.o),high:n(k.h),low:n(k.l),close:n(k.c),volume:n(k.v),closeTime:Number(k.T),quoteVolume:n(k.q)};if(!Number.isFinite(candle.openTime)||![candle.open,candle.high,candle.low,candle.close,candle.volume].every(Number.isFinite))return;slot.lastEventTime=Number(data?.E)||Date.now();if(k.x===true){const idx=slot.closed.findIndex(x=>x.openTime===candle.openTime);if(idx>=0)slot.closed[idx]=candle;else slot.closed.push(candle);slot.closed.sort((a,b)=>a.openTime-b.openTime);const keep=this.options.candleLimit+30;if(slot.closed.length>keep)slot.closed.splice(0,slot.closed.length-keep);if(slot.current?.openTime===candle.openTime)slot.current=null;}else slot.current=candle;this.recordPrice(symbol,candle.close,slot.lastEventTime);}
    recordPrice(symbol,price,time=Date.now()){if(!(price>0))return;let a=this.priceHistory.get(symbol);if(!a){a=[];this.priceHistory.set(symbol,a);}const last=a.at(-1);if(last&&time-last.time<200){last.price=price;last.time=time;}else a.push({time,price});const cutoff=time-120000;while(a.length&&a[0].time<cutoff)a.shift();}
    recentPrices(symbol,windowMs,referenceTime=Date.now()){const a=this.priceHistory.get(symbol)||[],cutoff=referenceTime-windowMs;return a.filter(x=>x.time>=cutoff&&x.time<=referenceTime+2000);}
    book(symbol){const b=this.books.get(symbol)||null;if(!b)return null;return Date.now()-Number(b.time||0)>this.options.staleMs?null:b;}
    bookMap(rows){const m=new Map();for(const x of rows||[]){const symbol=typeof x==='string'?x:x?.symbol;if(!symbol)continue;const b=this.book(symbol);if(b)m.set(symbol,b);}return m;}
    isReady(symbol,timeframes=null){timeframes=timeframes||this.options.requiredTimeframes||['5m','3m','1m'];return timeframes.every(tf=>this._interval(symbol,tf).bootstrapped&&this._interval(symbol,tf).closed.length>=this.options.candleLimit);}
    isHistoryReady(symbol){return this.isReady(symbol,this.options.requiredTimeframes||['5m','3m','1m']);}
    readySymbols(rows,timeframes){return (rows||[]).filter(x=>this.isReady(typeof x==='string'?x:x.symbol,timeframes));}
    getSnapshot(symbol,interval,serverTime){const slot=this._interval(symbol,interval),closed=slot.closed.filter(c=>c.closeTime<serverTime).slice(-this.options.candleLimit);if(!slot.bootstrapped||closed.length<this.options.candleLimit)throw new Error(`${interval} WebSocket cache warming ${closed.length}/${this.options.candleLimit}`);return {closed,current:slot.current};}
    health(rows,timeframes=null){timeframes=timeframes||this.options.requiredTimeframes||['5m','3m','1m'];const symbols=(rows||[]).map(x=>typeof x==='string'?x:x.symbol).filter(Boolean),t=Date.now(),one=tf=>symbols.filter(s=>{const x=this._interval(s,tf);return x.lastEventTime>0&&t-x.lastEventTime<=this.options.staleMs;}).length,book=symbols.filter(s=>{const b=this.books.get(s);return b&&Number(b.wsTime)>0&&t-Number(b.wsTime)<=this.options.staleMs;}).length,out={total:symbols.length,book};for(const tf of timeframes)out[tf]=one(tf);out.m1=out['1m']??0;out.m3=out['3m']??0;out.m5=out['5m']??0;out.m15=out['15m']??0;return out;}
  }
  class SubscriptionClient{constructor(name,baseUrl,onPayload,{log=()=>{},reconnectMaxMs=DEFAULTS.reconnectMaxMs}={}){this.name=name;this.baseUrl=baseUrl;this.onPayload=onPayload;this.log=log;this.reconnectMaxMs=reconnectMaxMs;this.ws=null;this.streams=[];this.stopped=true;this.reconnectMs=1000;this.reconnectTimer=null;}start(streams){this.streams=[...new Set(streams||[])].filter(Boolean);this.stopped=false;this._connect();}stop(){this.stopped=true;if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.reconnectTimer=null;try{this.ws?.close();}catch(_){}this.ws=null;}_connect(){if(this.stopped||!this.streams.length)return;try{this.ws=new WebSocket(`${this.baseUrl}/stream?streams=${this.streams.join('/')}`);}catch(e){this.log(`${this.name} WebSocket create failed: ${e?.message||e}`);this._schedule();return;}this.ws.addEventListener('open',()=>{this.reconnectMs=1000;this.log(`${this.name} WebSocket connected (${this.streams.length} combined streams).`);});this.ws.addEventListener('message',event=>{try{const msg=JSON.parse(event.data);if(msg&&msg.code!=null&&msg.msg){this.log(`${this.name} WebSocket error ${msg.code}: ${msg.msg}`);return;}this.onPayload(msg?.data??msg,msg);}catch(e){console.debug(`${this.name} payload error`,e);}});this.ws.addEventListener('error',()=>this.log(`${this.name} WebSocket transport error.`));this.ws.addEventListener('close',event=>{if(!this.stopped){this.log(`${this.name} WebSocket closed (${event?.code||0}${event?.reason?`: ${event.reason}`:''}); reconnecting.`);this._schedule();}});}_schedule(){if(this.stopped||this.reconnectTimer)return;const delay=this.reconnectMs;this.reconnectMs=Math.min(this.reconnectMaxMs,Math.round(this.reconnectMs*1.8));this.reconnectTimer=setTimeout(()=>{this.reconnectTimer=null;this._connect();},delay);}}
  class BinanceStreamService{
    constructor(options={}){this.options={...DEFAULTS,...options};this.log=this.options.log||(()=>{});this.store=this.options.store||new MarketDataStore(this.options);this.marketClients=[];this.publicClients=[];}
    start(universe,timeframes=null){timeframes=(timeframes&&timeframes.length?timeframes:this.options.requiredTimeframes||['5m','3m','1m']).slice();this.options.requiredTimeframes=timeframes.slice();if(this.store?.options)this.store.options.requiredTimeframes=timeframes.slice();this.stop();const symbols=(universe||[]).map(x=>String(x?.symbol||x)).filter(Boolean),market=[];for(const s of symbols){const x=s.toLowerCase();for(const tf of timeframes)market.push(`${x}@kline_${tf}`);}for(let i=0;i<market.length;i+=this.options.streamsPerSocket){const c=new SubscriptionClient(`Market#${this.marketClients.length+1}`,this.options.marketEndpoint,p=>{if(p?.e==='kline')this.store.applyKline(p);},{log:this.log,reconnectMaxMs:this.options.reconnectMaxMs});this.marketClients.push(c);c.start(market.slice(i,i+this.options.streamsPerSocket));}const books=symbols.map(s=>`${s.toLowerCase()}@bookTicker`);for(let i=0;i<books.length;i+=this.options.streamsPerSocket){const c=new SubscriptionClient(`Public#${this.publicClients.length+1}`,this.options.publicEndpoint,p=>{if(p?.e==='bookTicker'||(p?.s&&p?.b!=null&&p?.a!=null))this.store.applyBook(p);},{log:this.log,reconnectMaxMs:this.options.reconnectMaxMs});this.publicClients.push(c);c.start(books.slice(i,i+this.options.streamsPerSocket));}this.log(`WebSocket combined streams: market ${this.marketClients.length} socket(s), public ${this.publicClients.length} socket(s).`);}
    stop(){for(const c of this.marketClients)c.stop();for(const c of this.publicClients)c.stop();this.marketClients=[];this.publicClients=[];}
  }
  globalThis.BinanceStreamService=Object.freeze({BinanceStreamService,MarketDataStore,SubscriptionClient,DEFAULTS});
})();
